In [2]:
using VMLS
using LinearAlgebra

## Chapter 6
# Matrices
### 6.1 Matrices
**Creating matrices from the entries.** Matrices are represented in Julia as $2$-dimensional arrays. These are constructed by giving the elements in each row, separated by space, with the rows separated by semicolons. For example, the $3 × 4$ matrix
$$
A = \begin{bmatrix}
 0 & 1 & −2.3 & 0.1\\
 1.3 & 4.0 & −0.1 & 0\\
 4.1 & −1.0 & 0 & 1.7
\end{bmatrix}
$$
is constructed in Julia as

In [1]:
A = [0.0 1.0 -2.3 0.1;
    1.3 4.0 -0.1 0.0;
    4.1 -1.0 0.0 1.7]

3×4 Array{Float64,2}:
 0.0   1.0  -2.3  0.1
 1.3   4.0  -0.1  0.0
 4.1  -1.0   0.0  1.7

(Here, `Array{Float64,2}` above the array tells us that the array is $2$-dimensional, and its entries are `64-bit` floating-point numbers.) In this example, we put the different rows of the matrix on different lines, which makes the code more readable, but there is no need to do this; we get the same matrix with

In [2]:
A = [0 1 -2.3 0.1; 1.3 4 -0.1 0; 4.1 -1 0 1.7]

3×4 Array{Float64,2}:
 0.0   1.0  -2.3  0.1
 1.3   4.0  -0.1  0.0
 4.1  -1.0   0.0  1.7

The Julia function `size(A)` gives the size, as a tuple. It can also be called as `size(A,1)` or `size(A,2)` to get only the number of rows or columns. As an example, we create a function that determines if a matrix is tall.

In [4]:
m, n = size(A)
m

3

In [5]:
n

4

In [7]:
size(A,1)

3

In [8]:
size(A,2)

4

In [9]:
tall(X) = size(X,1)>size(X,2);
tall(A)

false

In the function definition, the number of rows and the number of columns are combined using the relational operator `<`, which gives a $Boolean$.

**Indexing entries.** We get the $i, j$ entry of a matrix `A` using `A[i,j]`. We can also assign a new value to an entry.

In [10]:
A[2,3] # Get 2,3 entry of A

-0.1

In [12]:
A[1,3] = 7.5; # Set 1,3 entry of A to 7.5
A

3×4 Array{Float64,2}:
 0.0   1.0   7.5  0.1
 1.3   4.0  -0.1  0.0
 4.1  -1.0   0.0  1.7

**Single index indexing.** Julia allows you to access an entry of a matrix using only one index. To use this, you need to know that matrices in Julia are stored in column-major order. This means that a matrix can be considered as a one - dimensional array, with the first column stacked on top of the second, stacked on top of the third, and so on. For example, the elements of the matrix
$$
Z =
\begin{bmatrix}
−1 & 0 & 2\\
−1 & 2 & 3
\end{bmatrix}
$$
are stored in the order
$$−1, −1, 0, 2, 2, 3.$$
With single index indexing, `Z[5]` is the fifth element in this sequence.

In [13]:
Z = [ -1 0 2; -1 2 -3];
Z[5]

2

This is very much not standard mathematical notation, and we would never use this in VMLS. But it can be handy in some cases when you are using Julia. 

**Equality of matrices.** `A == B` determines whether the matrices `A` and `B` are equal. The expression `A .== B` creates a matrix whose entries are $Boolean$, depending on whether the corresponding entries of `A` and `B` are the same. The expression `sum(A .== B)` gives the number of entries of `A` and `B` that are equal.

In [18]:
B = copy(A);
B[2,2] = 0;

A == B

false

In [19]:
A .== B

3×4 BitArray{2}:
 true   true  true  true
 true  false  true  true
 true   true  true  true

**Row and column vectors.** In Julia, as in VMLS, $n$-vectors are the same as $n × 1$ matrices.

In [20]:
a = [ -2.1 -3 0 ] # A 3-row vector or 1x3 matrix

1×3 Array{Float64,2}:
 -2.1  -3.0  0.0

In [21]:
b = [ -2.1; -3; 0 ] # A 3-vector or 3x1 matrix

3-element Array{Float64,1}:
 -2.1
 -3.0
  0.0

The output reveals a small subtlety that generally won’t affect you. You can see that b has type `Array{Float64,1}`. The final `1` means that it is a $1D$ array; `size(b)` gives `(3,)`, whereas you might think it would or should be `(3,1)`. So you might say that in Julia, $n × 1$ matrices are n-vectors. This is why we say above that n-vectors and $n × 1$ matrices are almost the same in Julia. 

**Slicing and submatrices.** Using colon notation you can extract a submatrix.

In [22]:
A = [ -1 0 1 0 ; 2 -3 0 1 ; 0 4 -2 1]

3×4 Array{Int64,2}:
 -1   0   1  0
  2  -3   0  1
  0   4  -2  1

In [23]:
A[1:2,3:4]

2×2 Array{Int64,2}:
 1  0
 0  1

This is very similar to the mathematical notation in VMLS, where this submatrix would be denoted $A_{1:2,3:4}$. You can also assign a submatrix using slicing (index range) notation. A very useful shortcut is the index range `:` which refers to the whole index range for that index. This can be used to extract the rows and columns of a matrix.

In [24]:
A[:,3] # Third column of A

3-element Array{Int64,1}:
  1
  0
 -2

In [26]:
A[2,:] # Second row of A, returned as column vector!

4-element Array{Int64,1}:
  2
 -3
  0
  1

In mathematical (VMLS) notation, we say that `A[2,:]` returns the transpose of the second row of `A`. As with vectors, Julia’s slicing and selection is not limited to contiguous ranges of indexes. For example, we can reverse the order of the rows of a matrix `X` using

In [30]:
X = copy(A) #For example
m = size(X,1)
X[m:-1:1,:] # Matrix X with row order reversed

3×4 Array{Int64,2}:
  0   4  -2  1
  2  -3   0  1
 -1   0   1  0

Julia’s single indexing for matrices can be used with index ranges or sets. For example if $X$ is an $m × n$ matrix, `X[:]` is a vector of size $mn$ that consists of the columns of `X` stacked on top of each other. The Julia function `reshape(X,(k,l))` gives a new $k × l$ matrix, with the entries taken in the column-major order from `X`. (We must have $mn = kl$, i.e., the original and reshaped matrix must have the same number of entries.) Neither of these is standard mathematical notation, but they can be useful in Julia.

In [32]:
B = [ 1 -3 ; 2 0 ; 1 -2]

3×2 Array{Int64,2}:
 1  -3
 2   0
 1  -2

In [33]:
B[:]

6-element Array{Int64,1}:
  1
  2
  1
 -3
  0
 -2

In [34]:
reshape(B,(2,3))

2×3 Array{Int64,2}:
 1   1   0
 2  -3  -2

In [35]:
reshape(B,(3,3))

DimensionMismatch: DimensionMismatch("new dimensions (3, 3) must be consistent with array size 6")

**Block matrices.** Block matrices are constructed in Julia very much as in the standard mathematical notation in VMLS. You use `;` to stack matrices, and a `space` to do (horizontal) concatenation. We apply this to the example on page [109](https://web.stanford.edu/~boyd/vmls/vmls.pdf#equation.6.1.1) of VMLS.

In [36]:
B = [ 0 2 3 ]; # 1x3 matrix

C = [ -1 ]; # 1x1 matrix

D = [ 2 2 1 ; 1 3 5]; # 2x3 matrix

E = [4 ; 4 ]; # 2x1 matrix

# construct 3x4 block matrix

A = [B C ; 
    D E]

3×4 Array{Int64,2}:
 0  2  3  -1
 2  2  1   4
 1  3  5   4

**Column and row interpretation of a matrix.** An $m × n$ matrix $A$ can be interpreted as a collection of $n$ $m$-vectors (its columns) or a collection of $m$ row vectors (its rows). Julia distinguishes between a matrix (a two-dimensional array) and an array of vectors. An array (or a tuple) of column vectors can be converted into a matrix using the horizontal concatenation function `hcat`.

In [37]:
a = [ [1., 2.], [4., 5.], [7., 8.] ] # array of 2-vectors

3-element Array{Array{Float64,1},1}:
 [1.0, 2.0]
 [4.0, 5.0]
 [7.0, 8.0]

In [38]:
A = hcat(a...)

2×3 Array{Float64,2}:
 1.0  4.0  7.0
 2.0  5.0  8.0

The `...` operator in `hcat(a...)` splits the array `a` into its elements, i.e., `hcat(a...)` is the same as `hcat(a[1], a[2], a[3])`, which concatenates `a[1], a[2], a[3]` horizontally. Similarly, `vcat` concatenates an array of arrays vertically. This is useful when constructing a matrix from its row vectors.

In [39]:
a = [ [1. 2.], [4. 5.], [7. 8.] ] # array of 1x2 matrices

3-element Array{Array{Float64,2},1}:
 [1.0 2.0]
 [4.0 5.0]
 [7.0 8.0]

In [40]:
A = vcat(a...)

3×2 Array{Float64,2}:
 1.0  2.0
 4.0  5.0
 7.0  8.0

### 6.2 Zero and identity matrices
**Zero matrices.** A zero matrix of size m× n is created using zeros(m,n).

In [41]:
zeros(2,2)

2×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0

**Identity matrices.** Identity matrices in Julia can be created many ways, for example by starting with a zero matrix and then setting the diagonal entries to one.

The `LinearAlgebra` package also contains functions for creating a special identity matrix object `I`, which has some nice features. You can use `1.0*Matrix(I,n,n)` to create an `n× n` identity matrix. (Multiplying by $1.0$ converts the matrix into one with numerical entries; otherwise it has $Boolean$ entries.) This expression is pretty unwieldy, so we can define a function `eye(n)` to generate an identity matrix. This function is in the `VMLS` package, so you can use it once the package is installed. (The name `eye` to denote the identity matrix `I` traces back to the `MATLAB` language.)

In [44]:
eye(n) = 1.0*Matrix(I,n,n)
eye(4)

4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

Julia’s identity matrix `I` has some useful properties. For example, when it can deduce its dimensions, you don’t have to specify it. (This is the same as with common mathematical notation; see VMLS page [113](https://web.stanford.edu/~boyd/vmls/vmls.pdf#section*.135).)

In [45]:
A = [ 1 -1 2; 0 3 -1]

2×3 Array{Int64,2}:
 1  -1   2
 0   3  -1

In [46]:
[A I]

2×5 Array{Int64,2}:
 1  -1   2  1  0
 0   3  -1  0  1

In [47]:
[A ; I]

5×3 Array{Int64,2}:
 1  -1   2
 0   3  -1
 1   0   0
 0   1   0
 0   0   1

In [48]:
B = [ 1 2 ; 3 4 ]

2×2 Array{Int64,2}:
 1  2
 3  4

In [49]:
B + I

2×2 Array{Int64,2}:
 2  2
 3  5

**Ones matrix.** In VMLS we do not have notation for a matrix with all entries one. In Julia, such a matrix is given by `ones(m,n)`. 

**Diagonal matrices.** In standard mathematical notation, `diag(1, 2, 3)` is a diagonal $3 × 3$ matrix with diagonal entries $1, 2, 3$. In Julia such a matrix is created using the function `diagm`, provided in the `LinearAlgebra` package. To construct the diagonal matrix with diagonal entries in the vector `s`, you use `diagm(0 => s)`. This is fairly unwieldy, so the `VMLS` package defines a function `diagonal(s)`. (Note that you have to pass the diagonal entries as a vector.)

In [50]:
 diagonal(x) = diagm(0 => x)

diagonal (generic function with 1 method)

In [51]:
diagonal([1,2,3])

3×3 Array{Int64,2}:
 1  0  0
 0  2  0
 0  0  3

A closely related Julia function `diag(X)` does the opposite: It takes the diagonal entries of the (possibly not square) matrix `X` and puts them into a vector.

In [52]:
H = [0 1 -2 1; 2 -1 3 0]

2×4 Array{Int64,2}:
 0   1  -2  1
 2  -1   3  0

In [53]:
diag(H)

2-element Array{Int64,1}:
  0
 -1

**Random matrices.** A random $m×n$ matrix with entries between $0$ and $1$ is created using `rand(m,n)`. For entries that have a normal distribution, `randn(m,n)`.

In [54]:
rand(2,3)

2×3 Array{Float64,2}:
 0.41485  0.482054  0.912613
 0.49318  0.850034  0.910118

In [55]:
randn(3,2)

3×2 Array{Float64,2}:
  0.311996  -0.342588
 -1.36241    0.453486
  0.935138  -0.59365 

Sparse matrices. Functions for creating and manipulating sparse matrices are contained in the SparseArrays package, which must be installed; see page ix. Sparse matrices are stored in a special format that exploits the property that most of the elements are zero. The sparse function creates a sparse matrix from three arrays that specify the row indexes, column indexes, and values of the nonzero elements. The following code creates a sparse matrix

$$
  A = 
  \begin{bmatrix} 
  −1.11 &  0.00 &  1.17 &  0.00 &  0.00 \\
  0.15  & −0.10 &  0.00 &  0.00 &  0.00 \\
  0.00  & 0.00  & −0.30 &  0.00 &  0.00 \\
  0.00  & 0.00  & 0.00  & 0.13  & 0.00 
  \end{bmatrix}.
$$

In [60]:
using SparseArrays

In [63]:
M = [ 1, 2, 2, 1, 3, 4 ] # row indexes of nonzeros
N = [ 1, 1, 2, 3, 3, 4 ] # column indexes
V = [ -1.11, 0.15, -0.10, 1.17, -0.30, 0.13 ] # values
A = sparse(M, N, V, 4, 5)

4×5 SparseMatrixCSC{Float64,Int64} with 6 stored entries:
  [1, 1]  =  -1.11
  [2, 1]  =  0.15
  [2, 2]  =  -0.1
  [1, 3]  =  1.17
  [3, 3]  =  -0.3
  [4, 4]  =  0.13

In [64]:
nnz(A)

6

Sparse matrices can be converted to regular non-sparse matrices using the `Array` function. Applying `sparse` to a full matrix gives the equivalent sparse matrix.

In [65]:
A = sparse([1, 3, 2, 1], [1, 1, 2, 3],
    [1.0, 2.0, 3.0, 4.0], 3, 3)

3×3 SparseMatrixCSC{Float64,Int64} with 4 stored entries:
  [1, 1]  =  1.0
  [3, 1]  =  2.0
  [2, 2]  =  3.0
  [1, 3]  =  4.0

In [66]:
B = Array(A)

3×3 Array{Float64,2}:
 1.0  0.0  4.0
 0.0  3.0  0.0
 2.0  0.0  0.0

In [67]:
B[1,3] = 0.0;
sparse(B)

3×3 SparseMatrixCSC{Float64,Int64} with 3 stored entries:
  [1, 1]  =  1.0
  [3, 1]  =  2.0
  [2, 2]  =  3.0

A sparse $m × n$ zero matrix is created with spzeros(m,n). To create a sparse $n × n$ identity matrix in Julia, use `sparse(1.0I,n,n)`. This is not a particularly natural syntax, so we define a function `speye(n)` in the `VMLS` package. The VMLS package also includes the function `speye(n)` which creates a sparse $n × n$ identity matrix, as well as `spdiagonal(a)`, which creates a sparse diagonal matrix with the entries of the vector a on its diagonal. 

A useful function for creating a random sparse matrix is sprand(m,n,d) (with entries between $0$ and $1$) and `sprandn(m,n,d)` (with entries that range over all numbers). The first two arguments give the dimensions of the matrix; the last one, `d`, gives the density of nonzero entries. The nonzero entries are chosen randomly, with about $mnd$ of them nonzero. The following code creates a random $10000 × 10000$ sparse matrix, with a density $10^{−7}$. This means that we’d expect there to be around $10$ nonzero entries. (So this is a *very* sparse matrix!)

In [68]:
A = sprand(10000,10000,10^-7)

10000×10000 SparseMatrixCSC{Float64,Int64} with 7 stored entries:
  [2633 ,    90]  =  0.408501
  [33   ,   723]  =  0.404502
  [8559 ,   824]  =  0.496639
  [5953 ,  3906]  =  0.982507
  [7401 ,  3973]  =  0.631249
  [3978 ,  4172]  =  0.753699
  [3427 ,  8290]  =  0.248351

### 6.3 Transpose, addition, and norm
**Transpose.** In VMLS we denote the transpose of an $m × n$ matrix $A$ as $A^T$ . In Julia, the transpose of $A$ is given by `A'`.

In [69]:
H = [0 1 -2 1; 2 -1 3 0]

2×4 Array{Int64,2}:
 0   1  -2  1
 2  -1   3  0

In [70]:
H'

4×2 Adjoint{Int64,Array{Int64,2}}:
  0   2
  1  -1
 -2   3
  1   0

**Addition, subtraction, and scalar multiplication.** In Julia, addition and subtraction of matrices, and scalar-matrix multiplication, both follow standard mathematical notation.

In [75]:
U = [ 0 4; 7 0; 3 1]

3×2 Array{Int64,2}:
 0  4
 7  0
 3  1

In [76]:
V = [ 1 2; 2 3; 0 4]

3×2 Array{Int64,2}:
 1  2
 2  3
 0  4

In [77]:
U+V

3×2 Array{Int64,2}:
 1  6
 9  3
 3  5

In [78]:
2.2*U

3×2 Array{Float64,2}:
  0.0  8.8
 15.4  0.0
  6.6  2.2

(We can also multiply a matrix on the right by a scalar.) 

Julia supports some operations that are not standard mathematical ones. For example, in Julia you can add or subtract a constant from a matrix, which carries out the operation on each entry. 

**Elementwise operations.** The syntax for elementwise vector operations described on page 10 carries over naturally to matrices. We add a period before a binary operator to change the interpretation to elementwise. For example, if $A$ and $B$ are matrices of the same size, then `C = A .* B` creates a matrix of the same size with elements $C_{ij} = A_{ij}B_{ij}$ . We can add a period after a function name to tell Julia that the function should be applied elementwise. Thus, if `X` is a matrix, then `Y = exp.(X)` creates a matrix of the same size, with elements $Y_{ij} = exp(X_{ij})$.

**Matrix norm.** In $VMLS$ we use $‖A‖$ to denote the norm of an $m × n$ matrix, 

$$
‖A‖ = \left(\sum_{i=1}^{m}\sum_{j=1}^{n}A^{2}_{ij}\right)^{\frac{1}{2}}.
$$

In standard mathematical notation, this is more often written as $‖A‖F$ , where $F$ stands for the name Frobenius. In standard mathematical notation, $‖A‖$ usually refers to another norm of a matrix, that is beyond the scope of the topics in VMLS. In Julia, `norm(A)` gives the norm used in VMLS.

In [3]:
A = [2 3 -1; 0 -1 4]
norm(A),norm(A[:])

(5.5677643628300215, 5.5677643628300215)

**Triangle inequality.** Let’s check that the triangle inequality $‖A+B‖ ≤ ‖A‖+‖B‖$ holds, for two specific matrices.

In [4]:
A = [-1 0; 2 2]; B= [3 1; -3 2];
norm(A + B), norm(A) + norm(B)

(4.69041575982343, 7.795831523312719)

### 6.4 Matrix-vector multiplication
In Julia, matrix-vector multiplication has the natural syntax `y=A*x`.

In [7]:
A = [0 2 -1; -2 1 1]
x = [2, 1, -1]
A*x

2-element Array{Int64,1}:
  3
 -4

**Difference matrix.** An $(n − 1) × n$ difference matrix (equation ([6.5](https://web.stanford.edu/~boyd/vmls/vmls.pdf#equation.6.4.6)) of VMLS) can be constructed in several ways. A simple one is the following.

In [27]:
difference_matrix(n) = [-eye(n-1) zeros(n-1)] + [zeros(n-1) eye(n-1)];
D = difference_matrix(4)

3×4 Array{Float64,2}:
 -1.0   1.0   0.0  0.0
  0.0  -1.0   1.0  0.0
  0.0   0.0  -1.0  1.0

In [28]:
D*[-1,0,2,1]

3-element Array{Float64,1}:
  1.0
  2.0
 -1.0

Since a difference matrix contains many zeros, this is a good opportunity to use
sparse matrices.

In [31]:
using SparseArrays

In [32]:
difference_matrix(n) = [-speye(n-1) spzeros(n-1)] + [spzeros(n-1) speye(n-1)];
D = difference_matrix(4)

3×4 SparseMatrixCSC{Float64,Int64} with 6 stored entries:
  [1, 1]  =  -1.0
  [1, 2]  =  1.0
  [2, 2]  =  -1.0
  [2, 3]  =  1.0
  [3, 3]  =  -1.0
  [3, 4]  =  1.0

In [33]:
D*[-1,0,2,1]

3-element Array{Float64,1}:
  1.0
  2.0
 -1.0

**Running sum matrix.** The running sum matrix (equation ([6.6](https://web.stanford.edu/~boyd/vmls/vmls.pdf#equation.6.4.6)) in VMLS) is a lower triangular matrix, with elements on and below the diagonal equal to one.

In [34]:
function running_sum(n) # n x n running sum matrix
    S = zeros(n,n)
    for i=1:n
        for j=1:i
            S[i,j] = 1
        end
    end
    return S
end

running_sum (generic function with 1 method)

In [35]:
running_sum(4)*[-1,1,2,0]

4-element Array{Float64,1}:
 -1.0
  0.0
  2.0
  2.0

An alternative construction is `tril(ones(n,n))`. This uses the function `tril`, which sets the elements of a matrix above the diagonal to zero. Vandermonde matrix. An $m×n$ Vandermonde matrix (equation ([6.7](https://web.stanford.edu/~boyd/vmls/vmls.pdf#equation.6.4.7)) in VMLS) has entries $t^{j−1}_i$ for $i = 1, . . . ,m$ and $j = 1, . . . , n$. We define a function that takes an $m$-vector with elements $t_1, . . . , t_m$ and returns the corresponding $m × n$ Vandermonde matrix.

In [36]:
function vandermonde(t,n)
    m = length(t)
    V = zeros(m,n)
    for i=1:m
        for j=1:n
            V[i,j] = t[i]^(j-1)
        end
    end
    return V
end

vandermonde (generic function with 1 method)

In [37]:
vandermonde([-1,0,0.5,1],5)

4×5 Array{Float64,2}:
 1.0  -1.0  1.0   -1.0    1.0   
 1.0   0.0  0.0    0.0    0.0   
 1.0   0.5  0.25   0.125  0.0625
 1.0   1.0  1.0    1.0    1.0   

An alternative shorter definition uses Julia’s `hcat` function.

In [38]:
vandermonde(t,n) = hcat( [t.^i for i = 0:n-1]... )

vandermonde (generic function with 1 method)

In [39]:
vandermonde([-1,0,0.5,1],5)

4×5 Array{Float64,2}:
 1.0  -1.0  1.0   -1.0    1.0   
 1.0   0.0  0.0    0.0    0.0   
 1.0   0.5  0.25   0.125  0.0625
 1.0   1.0  1.0    1.0    1.0   

### 6.5 Complexity
**Complexity of matrix-vector multiplication.** The complexity of multiplying an
$m×n$ matrix by an $n$-vector is $2mn$ flops. This grows linearly with both $m$ and $n$.
Let’s check this.

In [40]:
A = rand(1000,10000); x = rand(10000);
@time y = A*x;
@time y = A*x;
A = rand(5000,20000); x = rand(20000);
@time y = A*x;
@time y = A*x;

  0.009904 seconds (7.85 k allocations: 450.466 KiB)
  0.004259 seconds (5 allocations: 8.094 KiB)
  0.043273 seconds (6 allocations: 39.297 KiB)
  0.038998 seconds (6 allocations: 39.297 KiB)


In the second matrix-vector multiply, $m$ increases by a factor of $5$ and $n$ increases by a factor of $2$, so the complexity predicts that the computation time should be (approximately) increased by a factor of $10$. As we can see, it is increased by a factor around $7.4$. The increase in efficiency obtained by sparse matrix computations is seen from matrix-vector multiplications with the difference matrix.

In [41]:
n = 10^4;
D = [-eye(n-1) zeros(n-1)] + [zeros(n-1) eye(n-1)];
x = randn(n);
@time y=D*x;
Ds = [-speye(n-1) spzeros(n-1)] + [spzeros(n-1) speye(n-1)];
@time y=Ds*x;

  0.049277 seconds (6 allocations: 78.359 KiB)
  0.035362 seconds (51.89 k allocations: 2.720 MiB)
